(()=>{
const APP='Plant Secretary',BACKUP_VERSION=1;
const $=s=>document.querySelector(s);
function plantsList(){try{return typeof plants!=='undefined'?plants:(window.plants||[])}catch(e){return window.plants||[]}}
function showSheet(title,html){let m=$('#utilityModal');if(!m){m=document.createElement('div');m.id='utilityModal';m.className='modal';m.innerHTML='<div class="sheet"><div class="sheethead"><h3 id="utilityTitle"></h3><button class="close" id="utilityClose">×</button></div><div id="utilityBody"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});m.querySelector('#utilityClose').onclick=()=>m.classList.remove('open')}m.querySelector('#utilityTitle').textContent=title;m.querySelector('#utilityBody').innerHTML=html;m.classList.add('open');m.querySelector('.sheet').scrollTop=0}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const GUIDE_TOPICS=['Plant features','Sunlight','Watering','Soil','pH','Feeding','Growth habit','Pruning','Pinching','Repotting','Propagation','Common problems','Seasonal care','Recommended products'];
const FIELD={'Sunlight':'sunlight','Watering':'water','Soil':'soil','pH':'ph','Feeding':'feed','Growth habit':'habit','Pruning':'prune','Pinching':'pinching','Repotting':'repotting','Propagation':'propagation','Common problems':'problems','Seasonal care':'seasonal'};
function currentPlant(){const name=document.querySelector('#modalTitle')?.textContent?.trim();return plantsList().find(p=>p.name===name)||null}
function botanicalCare(p){return window.PLANT_BOTANICAL_CARE?.get(p?.botanical)||null}
function issueFor(p){return window.PLANT_BOTANICAL_CARE?.identificationIssue(p?.botanical)||null}
function sourcePanel(c){return c?.source?`<div class="panel"><h3>Care basis</h3><p class="hint" style="margin:0;line-height:1.5">Botanical identity: <b>${esc(c.botanical)}</b><br>Source basis: ${esc(c.source)}</p></div>`:''}
function unavailable(p){const issue=issueFor(p);return `<div class="panel"><h3>Species-specific care unavailable</h3><p><b>${esc(issue||'This botanical identity is not yet in the verified care database.')}</b></p><p class="hint">Saved botanical name: ${esc(p?.botanical||'Not set')}</p><p>No generic care guide has been substituted.</p></div>`}
function fieldText(c,field){const v=c?.[field];if(Array.isArray(v))return v.filter(Boolean).join(' — ');return v||'Not established in the selected species-specific sources.'}
function topicHtml(name,p){
 const c=botanicalCare(p);if(!c)return unavailable(p);
 let body='';
 if(name==='Plant features')body=`<p><b>${esc(c.botanical)}</b></p><p>${esc(c.habit)}</p>`;
 else if(name==='Recommended products')body=`<p><b>No generic product has been substituted.</b></p><p>Choose a product only when its label and composition match this species-specific requirement:</p><p>${esc(fieldText(c,'soil'))}</p><p>${esc(fieldText(c,'feed'))}</p>`;
 else {const field=FIELD[name];body=`<p>${esc(fieldText(c,field))}</p>`}
 return `<div class="panel"><h3>${esc(p?.name||c.botanical)}</h3>${body}<p class="hint">Botanical basis: ${esc(c.botanical)}</p></div>${sourcePanel(c)}`
}
function generalGuides(){showSheet('Care Guides',`<p class="hint">Open a plant from My Plants for plant-specific recommendations.</p><div class="guide-list">${GUIDE_TOPICS.map(k=>`<button class="guide-row care-topic" data-topic="${esc(k)}" style="border:0;text-align:left;width:100%;color:inherit"><b>${esc(k)}</b><span>›</span></button>`).join('')}</div>${trusted}`)}
function topic(name,p=null){showSheet(name,topicHtml(name,p));if(!p){const b=document.createElement('button');b.className='secondary';b.textContent='← Care Guides';b.style.marginTop='10px';b.onclick=generalGuides;$('#utilityBody').appendChild(b)}}
function notes(){const ps=plantsList();showSheet('Plant Notes',`<div class="guide-list">${ps.map(p=>`<div class="guide-row"><div><b>${esc(p.name)}</b><div class="hint" style="margin:4px 0 0">${esc(p.notes||'No notes yet')}</div></div></div>`).join('')||'<p class="hint">No plants yet.</p>'}</div>`)}
function reminders(){const ps=plantsList();const rows=ps.map(p=>({p,d:typeof daysUntil==='function'?daysUntil(p):null})).filter(x=>x.d!==null).sort((a,b)=>a.d-b.d);showSheet('Reminders',`<div class="due-list">${rows.map(x=>`<div class="due-item"><b>${esc(x.p.name)}</b><span>${x.d<=0?'Check today':`in ${x.d} day${x.d===1?'':'s'}`}</span></div>`).join('')}</div>`)}
function weather(){showSheet('Weather',`<div class="panel"><h3>Altona, Victoria</h3><p class="hint">Live BOM weather is not yet connected in this build. Watering guidance uses the plant’s saved check interval plus actual potting-mix moisture. For outdoor plants, rainfall, heat and wind should modify the timing.</p></div>`)}
function settings(){showSheet('Settings',`<div class="panel"><h3>App preferences</h3><p class="hint">Plant Secretary stores plant care data locally on this device. Use Backup & Restore before clearing browser data or changing devices.</p></div>`)}
function about(){showSheet('About Plant Secretary',`<div class="panel"><h3>Plant Secretary</h3><p>Version ${(window.PLANT_SECRETARY_VERSION||'').replace(/^v/,'')}</p><p class="hint">Local-first personal plant care app.</p></div>`)}
function fileToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function photosExport(){const out={};try{const d=await db();const keys=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').getAllKeys();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});for(const k of keys){const b=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(b)out[k]=await fileToDataURL(b)}d.close()}catch(e){}return out}
async function exportBackup(){const payload={appName:APP,backupVersion:BACKUP_VERSION,exportedAt:new Date().toISOString(),data:{localStorage:{...localStorage},photos:await photosExport()}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`plant-secretary-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function dataURLBlob(s){const [h,b]=s.split(',');const mime=(h.match(/data:([^;]+)/)||[])[1]||'application/octet-stream';const bin=atob(b),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Blob([u],{type:mime})}
async function importBackup(file){let o;try{o=JSON.parse(await file.text())}catch(e){throw new Error('This file is not valid JSON.')}if(!o||o.appName!==APP||o.backupVersion!==BACKUP_VERSION||!o.data||typeof o.data.localStorage!=='object')throw new Error('This is not a valid Plant Secretary backup.');if(!confirm('Importing this backup will replace the app’s current saved data. Continue?'))return;localStorage.clear();Object.entries(o.data.localStorage).forEach(([k,v])=>localStorage.setItem(k,v));if(o.data.photos&&typeof o.data.photos==='object'){const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('photos','readwrite');const st=tx.objectStore('photos');st.clear();Object.entries(o.data.photos).forEach(([k,v])=>st.put(dataURLBlob(v),k));tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}alert('Backup restored. Plant Secretary will reload now.');location.reload()}
function backup(){showSheet('Backup & Restore',`<p class="hint">Export all supported saved app data to a JSON backup, or restore a Plant Secretary backup.</p><div class="actions"><button class="primary" id="exportBackup">Export backup</button><label class="secondary" style="text-align:center;cursor:pointer">Import backup<input id="importBackup" type="file" accept="application/json,.json" hidden></label></div><p class="hint" id="backupError" style="color:var(--danger);margin-top:12px"></p>`);$('#exportBackup').onclick=exportBackup;$('#importBackup').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await importBackup(f)}catch(err){$('#backupError').textContent=err.message}}}
const actions={'Care Guides':generalGuides,'Plant Notes':notes,'Reminders':reminders,'Weather':weather,'Backup & Restore':backup,'Settings':settings,'About Plant Secretary':about};
document.addEventListener('click',e=>{const card=e.target.closest('.more-card');if(card){const name=card.querySelector('b')?.textContent.trim();if(actions[name]){actions[name]();return}}const t=e.target.closest('.care-topic');if(t){topic(t.dataset.topic);return}const row=e.target.closest('#plantProfile .guide-row');if(row){const name=row.querySelector('b')?.textContent.trim();if(name){topic(name,currentPlant());return}}});
const st=document.createElement('style');st.textContent='.more-card{cursor:pointer}.more-card:active,.guide-row:active{transform:scale(.985)}#plantProfile .guide-row{cursor:pointer}#utilityBody ul{padding-left:20px;line-height:1.5}#utilityBody a.primary{color:white}';document.head.appendChild(st);
})();