(()=>{
const APP='Plant Secretary',BACKUP_VERSION=1;
const $=s=>document.querySelector(s);
function plantsList(){try{return typeof plants!=='undefined'?plants:(window.plants||[])}catch(e){return window.plants||[]}}
function showSheet(title,html){let m=$('#utilityModal');if(!m){m=document.createElement('div');m.id='utilityModal';m.className='modal';m.innerHTML='<div class="sheet"><div class="sheethead"><h3 id="utilityTitle"></h3><button class="close" id="utilityClose">×</button></div><div id="utilityBody"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});m.querySelector('#utilityClose').onclick=()=>m.classList.remove('open')}m.querySelector('#utilityTitle').textContent=title;m.querySelector('#utilityBody').innerHTML=html;m.classList.add('open');m.querySelector('.sheet').scrollTop=0}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const GUIDE_TOPICS=['Plant features','Sunlight','Watering checks','Soil','pH','Feeding','Growth habit','Pruning','Pinching','Repotting','Propagation','Common problems','Seasonal care','Recommended products'];
const FIELD={'Sunlight':'sunlight','Watering checks':'water','Watering':'water','Soil':'soil','pH':'ph','Feeding':'feed','Growth habit':'habit','Pruning':'prune','Pinching':'pinching','Repotting':'repotting','Propagation':'propagation','Common problems':'problems','Seasonal care':'seasonal'};
function currentPlant(){const id=$('#plantModal')?.dataset.plantId;return id?plantsList().find(p=>String(p.id)===String(id))||null:null}
function botanicalCare(p){return window.PLANT_BOTANICAL_CARE?.get(p?.botanical)||null}
function issueFor(p){return window.PLANT_BOTANICAL_CARE?.identificationIssue(p?.botanical)||null}
function sourcePanel(c,field){
 if(!c?.source)return '';
 const ids=c.fieldSources?.[field];
 const sources=(c.sources||[]).filter(s=>!ids||ids.includes(s.id));
 const links=sources.length?`<ul>${sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)}</a><br><span class="hint">${esc(s.scope)}</span></li>`).join('')}</ul>`:`<p class="hint">${esc(c.source)}</p>`;
 return `<div class="panel"><h3>Care basis</h3><p class="hint">Botanical identity: <b>${esc(c.botanical)}</b><br><b>Source hierarchy:</b> ${esc(c.sourcePolicy||window.PLANT_BOTANICAL_CARE?.sourcePolicy||'')}</p>${c.evidenceGaps?`<p class="hint"><b>Evidence gaps:</b> ${esc(c.evidenceGaps)}</p>`:''}<h4>${ids?'Sources for this field':'Sources used for this guide'}</h4>${links}${c.reviewedAt?`<p class="hint">Reviewed: ${esc(c.reviewedAt)}</p>`:''}</div>`
}
function unavailable(p){const issue=issueFor(p);return `<div class="panel"><h3>Species-specific care unavailable</h3><p><b>${esc(issue||'This botanical identity is not yet in the verified care database.')}</b></p><p class="hint">Saved botanical name: ${esc(p?.botanical||'Not set')}</p><p>No generic care guide has been substituted.</p></div>`}
function fieldText(c,field){const v=c?.[field];if(Array.isArray(v))return v.filter(Boolean).join(' — ');return v||'Not established in the selected species-specific sources.'}
function productHtml(c,field){
 const products=(c.products||[]).filter(p=>!field||p.field===field);
 if(!products.length)return '';
 return `<div><h4>Bunnings product matches</h4>${products.map(p=>`<p><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.name)}</a><br><span class="hint">${esc(p.basis)}</span></p>`).join('')}<p class="hint">Matched to the sourced requirement; brands are not endorsed by the botanical sources. Listings checked ${esc(c.reviewedAt||'')}; check your store for stock and read the current pack.</p></div>`
}
function topicHtml(name,p){
 const c=botanicalCare(p);if(!c)return unavailable(p);
 let body='';
 if(name==='Plant features')body=`<p><b>${esc(c.botanical)}</b></p><p>${esc(c.habit)}</p>${c.identityNote?`<p class="hint">${esc(c.identityNote)}</p>`:''}`;
 else if(name==='Recommended products')body=c.products?.length?productHtml(c):`<p><b>No generic product has been substituted.</b></p><p>Choose a product only when its label and composition match this species-specific requirement:</p><p>${esc(fieldText(c,'soil'))}</p><p>${esc(fieldText(c,'feed'))}</p>`;
 else {const field=FIELD[name];body=`<p>${esc(fieldText(c,field))}</p>${['soil','feed'].includes(field)?productHtml(c,field):''}`}
 if(FIELD[name]==='water')return `<div class="panel"><h3>Watering checks</h3><p>${esc(window.PLANT_WATERING_AUDIT.describe(p))}</p>${window.PLANT_WATERING_AUDIT.sources(p).map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)}</a><br><span class="hint">${esc(s.scope)}</span></p>`).join('')}</div>`;
 return `<div class="panel"><h3>${esc(p?.name||c.botanical)}</h3>${body}<p class="hint">Botanical basis: ${esc(c.botanical)}</p></div>${sourcePanel(c,name==='Plant features'?'habit':FIELD[name])}`
}
function generalGuides(){const ps=plantsList().slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));showSheet('Care Guides',`<p class="hint">Choose a plant to open its botanical-name-based care guide.</p><div class="guide-list">${ps.map(p=>`<button class="guide-row care-plant" data-plant-id="${esc(p.id)}" style="border:0;text-align:left;width:100%;color:inherit"><span><b>${esc(p.name)}</b><small class="hint" style="display:block;margin-top:3px">${esc(p.botanical||'Botanical name not set')}</small></span><span>›</span></button>`).join('')||'<p class="hint">No plants yet.</p>'}</div>`)}
function plantGuide(id){const p=plantsList().find(x=>String(x.id)===String(id));if(!p)return;const c=botanicalCare(p);showSheet(p.name,`${c?`<div class="panel"><p style="margin:0"><b>${esc(c.botanical)}</b></p><p class="hint" style="margin:4px 0 0">Care guide uses the saved botanical identity.</p></div>`:unavailable(p)}<div class="guide-list">${GUIDE_TOPICS.map(k=>`<button class="guide-row care-topic" data-topic="${esc(k)}" data-plant-id="${esc(p.id)}" style="border:0;text-align:left;width:100%;color:inherit"><b>${esc(k)}</b><span>›</span></button>`).join('')}</div>`)}
function topic(name,p=null){if(!p){generalGuides();return}showSheet(name,topicHtml(name,p));const b=document.createElement('button');b.className='secondary';b.textContent=`← ${p.name}`;b.style.marginTop='10px';b.onclick=()=>plantGuide(p.id);$('#utilityBody').appendChild(b)}
function noteSort(ps){const alpha=(a,b)=>String(a.name||'').localeCompare(String(b.name||''),undefined,{sensitivity:'base'});const indoor=ps.filter(p=>String(p.location||'').trim().toLowerCase()==='indoor').sort(alpha);const outdoor=ps.filter(p=>String(p.location||'').trim().toLowerCase()==='outdoor').sort(alpha);const other=ps.filter(p=>!['indoor','outdoor'].includes(String(p.location||'').trim().toLowerCase())).sort(alpha);return {indoor,outdoor,other}}
function noteRows(list){return list.map(p=>`<button type="button" class="guide-row plant-note-row" data-note-id="${esc(p.id)}" style="border:0;text-align:left;width:100%;color:inherit"><span><b>${esc(p.name)}</b><small class="hint" style="display:block;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:240px">${esc(p.notes||'No notes yet')}</small></span><span>›</span></button>`).join('')}
function notes(){const g=noteSort(plantsList());const section=(title,list)=>list.length?`<h3 style="margin:18px 0 8px">${title}</h3><div class="guide-list">${noteRows(list)}</div>`:'';showSheet('Plant Notes',`<p class="hint">Tap a plant to add or edit its note.</p>${section('Indoor',g.indoor)}${section('Outdoor',g.outdoor)}${section('Other',g.other)}${!g.indoor.length&&!g.outdoor.length&&!g.other.length?'<p class="hint">No plants yet.</p>':''}`)}
function editNote(id){const p=plantsList().find(x=>String(x.id)===String(id));if(!p)return;showSheet('Plant Note',`<div class="panel"><h3>${esc(p.name)}</h3><p class="hint" style="margin-top:4px">${esc(p.botanical||'Botanical name not set')}</p><label for="plantNoteText" style="display:block;font-weight:750;margin:12px 0 6px">Notes</label><textarea id="plantNoteText" rows="9" style="width:100%;box-sizing:border-box;resize:vertical;border:1px solid #d9e5e1;border-radius:14px;padding:12px;font:inherit;color:inherit;background:#fff">${esc(p.notes||'')}</textarea><div class="actions" style="margin-top:12px"><button type="button" class="primary" id="savePlantNote">Save note</button><button type="button" class="secondary" id="cancelPlantNote">Cancel</button></div></div>`);const area=$('#plantNoteText');$('#savePlantNote').onclick=()=>{p.notes=area.value.trim();if(typeof save==='function')save();if(typeof renderAll==='function')renderAll();notes();if(typeof toast==='function')toast(`Note saved for ${p.name}`)};$('#cancelPlantNote').onclick=notes;requestAnimationFrame(()=>{area?.focus();const n=area?.value.length||0;area?.setSelectionRange?.(n,n)})}
function reminders(){const ps=plantsList();const rows=ps.map(p=>({p,d:typeof daysUntil==='function'?daysUntil(p):null})).filter(x=>x.d!==null).sort((a,b)=>a.d-b.d);showSheet('Reminders',`<div class="due-list">${rows.map(x=>`<div class="due-item"><b>${esc(x.p.name)}</b><span>${x.d<=0?'Check today':`in ${x.d} day${x.d===1?'':'s'}`}</span></div>`).join('')}</div>`)}
function weather(){const a=window.PLANT_WATERING_AUDIT;showSheet('Weather',`<div class="panel"><h3>Altona, Victoria</h3><p class="hint">${esc(a?.weatherContext({location:'Outdoor'})||'Open BOM for the latest Altona forecast.')}</p><p><a href="https://www.bom.gov.au/places/vic/altona/forecast/" target="_blank" rel="noopener">BOM Altona forecast</a></p><p class="hint">Soil moisture decides whether to water. The stored forecast is dated and is not refreshed automatically.</p></div>`)}
function settings(){showSheet('Settings',`<div class="panel"><h3>App preferences</h3><p class="hint">Plant Secretary stores plant care data locally on this device. Use Backup & Restore before clearing browser data or changing devices.</p></div>`)}
function about(){showSheet('About Plant Secretary',`<div class="panel"><h3>Plant Secretary</h3><p>Version ${(window.PLANT_SECRETARY_VERSION||'').replace(/^v/,'')}</p><p class="hint">Local-first personal plant care app.</p></div>`)}
function fileToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function photosExport(){const out={};try{const d=await db();const keys=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').getAllKeys();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});for(const k of keys){const b=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(b)out[k]=await fileToDataURL(b)}d.close()}catch(e){}return out}
async function exportBackup(){const payload={appName:APP,backupVersion:BACKUP_VERSION,exportedAt:new Date().toISOString(),data:{localStorage:{...localStorage,'plant-secretary-v1':JSON.stringify(plantsList()),'plant-secretary-projects-v1':JSON.stringify(typeof projects!=='undefined'?projects:[])},photos:await photosExport()}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`plant-secretary-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function dataURLBlob(s){const [h,b]=s.split(',');const mime=(h.match(/data:([^;]+)/)||[])[1]||'application/octet-stream';const bin=atob(b),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Blob([u],{type:mime})}
async function importBackup(file){let o;try{o=JSON.parse(await file.text())}catch(e){throw new Error('This file is not valid JSON.')}if(!o||o.appName!==APP||o.backupVersion!==BACKUP_VERSION||!o.data||typeof o.data.localStorage!=='object')throw new Error('This is not a valid Plant Secretary backup.');if(!confirm('Importing this backup will replace the app’s current saved data. Continue?'))return;localStorage.clear();Object.entries(o.data.localStorage).forEach(([k,v])=>localStorage.setItem(k,v));if(o.data.photos&&typeof o.data.photos==='object'){const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('photos','readwrite');const st=tx.objectStore('photos');st.clear();Object.entries(o.data.photos).forEach(([k,v])=>st.put(dataURLBlob(v),k));tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}await window.PLANT_DATA_STORAGE.persist({plants:JSON.parse(localStorage.getItem('plant-secretary-v1')||'[]'),projects:JSON.parse(localStorage.getItem('plant-secretary-projects-v1')||'[]')});alert('Backup restored. Plant Secretary will reload now.');location.reload()}
function backup(){showSheet('Backup & Restore',`<p class="hint">Export all supported saved app data to a JSON backup, or restore a Plant Secretary backup.</p><div class="actions"><button class="primary" id="exportBackup">Export backup</button><label class="secondary" style="text-align:center;cursor:pointer">Import backup<input id="importBackup" type="file" accept="application/json,.json" hidden></label></div><p class="hint" id="backupError" style="color:var(--danger);margin-top:12px"></p>`);$('#exportBackup').onclick=exportBackup;$('#importBackup').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await importBackup(f)}catch(err){$('#backupError').textContent=err.message}}}
const actions={'Care Guides':generalGuides,'Plant Notes':notes,'Reminders':reminders,'Weather':weather,'Backup & Restore':backup,'Settings':settings,'About Plant Secretary':about};
document.addEventListener('click',e=>{const note=e.target.closest('.plant-note-row');if(note){editNote(note.dataset.noteId);return}const card=e.target.closest('.more-card');if(card){const name=card.querySelector('b')?.textContent.trim();if(actions[name]){actions[name]();return}}const plant=e.target.closest('.care-plant');if(plant){plantGuide(plant.dataset.plantId);return}const t=e.target.closest('.care-topic');if(t){const p=t.dataset.plantId?plantsList().find(x=>String(x.id)===String(t.dataset.plantId)):null;topic(t.dataset.topic,p);return}const row=e.target.closest('#plantProfile .guide-row');if(row){const name=row.querySelector('b')?.textContent.trim();if(name){topic(name,currentPlant());return}}});
const st=document.createElement('style');st.textContent='.more-card{cursor:pointer}.more-card:active,.guide-row:active{transform:scale(.985)}#plantProfile .guide-row{cursor:pointer}#utilityBody ul{padding-left:20px;line-height:1.5}#utilityBody a.primary{color:white}';document.head.appendChild(st);
})();
