(()=>{
const APP='Plant Secretary',BACKUP_VERSION=1;
const $=s=>document.querySelector(s);
function showSheet(title,html){let m=$('#utilityModal');if(!m){m=document.createElement('div');m.id='utilityModal';m.className='modal';m.innerHTML='<div class="sheet"><div class="sheethead"><h3 id="utilityTitle"></h3><button class="close" id="utilityClose">×</button></div><div id="utilityBody"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});m.querySelector('#utilityClose').onclick=()=>m.classList.remove('open')}m.querySelector('#utilityTitle').textContent=title;m.querySelector('#utilityBody').innerHTML=html;m.classList.add('open');m.querySelector('.sheet').scrollTop=0}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const care={
'Plant features':'Growth form, foliage and the features that make this plant distinctive.','Sunlight':'Use the sunlight icon and plant profile for its preferred light. Avoid abrupt changes in exposure.','Watering':'Check the plant and potting mix before watering. Home keeps the individual watering schedule.','Soil':'Use a free-draining mix appropriate to the species and container.','pH':'Use the plant’s saved pH preference as the guide for its potting medium.','Feeding':'Feed according to the plant, season and product label.','Growth habit':'Shows whether the plant is upright, climbing, trailing, clumping, spreading, shrub-like or tree-forming.','Pruning':'Remove damaged growth and prune according to the plant’s growth habit.','Pinching':'Pinch suitable soft-growing plants to encourage branching when required.','Repotting':'Repot when roots, drainage or potting-medium condition indicate it is needed.','Propagation':'Propagation method depends on the species: division, cuttings, offsets, seed or other suitable methods.','Common problems':'Check leaves, stems, roots and potting mix for pests, watering stress and environmental problems.','Seasonal care':'Adjust watering, feeding and exposure as growth and conditions change through the year.','Recommended products':'Choose products suitable for the plant and follow the product label.'};
function generalGuides(){showSheet('Care Guides',`<p class="hint">Plant-care topics. Open a plant in My Plants for its individual profile.</p><div class="guide-list">${Object.keys(care).map(k=>`<button class="guide-row care-topic" data-topic="${esc(k)}" style="border:0;text-align:left;width:100%;color:inherit"><b>${esc(k)}</b><span>›</span></button>`).join('')}</div>`)}
function topic(name){showSheet(name,`<div class="panel"><p style="line-height:1.5;margin:0">${esc(care[name]||'Care information for this plant.')}</p></div><button class="secondary" id="backGuides">← Care Guides</button>`);setTimeout(()=>{const b=$('#backGuides');if(b)b.onclick=generalGuides},0)}
function notes(){const ps=window.plants||[];showSheet('Plant Notes',`<div class="guide-list">${ps.map(p=>`<div class="guide-row"><div><b>${esc(p.name)}</b><div class="hint" style="margin:4px 0 0">${esc(p.notes||'No notes yet')}</div></div></div>`).join('')||'<p class="hint">No plants yet.</p>'}</div>`)}
function reminders(){const ps=window.plants||[];const rows=ps.map(p=>({p,d:typeof window.daysUntil==='function'?window.daysUntil(p):null})).filter(x=>x.d!==null).sort((a,b)=>a.d-b.d);showSheet('Reminders',`<div class="due-list">${rows.map(x=>`<div class="due-item"><b>${esc(x.p.name)}</b><span>${x.d<=0?'Check today':`in ${x.d} day${x.d===1?'':'s'}`}</span></div>`).join('')}</div>`)}
function weather(){showSheet('Weather',`<div class="panel"><h3>Altona, Victoria</h3><p class="hint">Weather data is not connected in this build. Watering records continue to use each plant’s saved schedule.</p></div>`)}
function settings(){showSheet('Settings',`<div class="panel"><h3>App preferences</h3><p class="hint">Plant Secretary currently stores plant care data locally on this device. Use Backup & Restore before clearing browser data or changing devices.</p></div>`)}
function about(){showSheet('About Plant Secretary',`<div class="panel"><h3>Plant Secretary</h3><p>Version 1.0.3</p><p class="hint">Local-first personal plant care app.</p></div>`)}
function fileToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function photosExport(){const out={};try{const d=await window.db();const keys=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').getAllKeys();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});for(const k of keys){const b=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(b)out[k]=await fileToDataURL(b)}d.close()}catch(e){}return out}
async function exportBackup(){const payload={appName:APP,backupVersion:BACKUP_VERSION,exportedAt:new Date().toISOString(),data:{localStorage:{...localStorage},photos:await photosExport()}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`plant-secretary-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function dataURLBlob(s){const [h,b]=s.split(',');const mime=(h.match(/data:([^;]+)/)||[])[1]||'application/octet-stream';const bin=atob(b),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Blob([u],{type:mime})}
async function importBackup(file){let o;try{o=JSON.parse(await file.text())}catch(e){throw new Error('This file is not valid JSON.')}if(!o||o.appName!==APP||o.backupVersion!==BACKUP_VERSION||!o.data||typeof o.data.localStorage!=='object')throw new Error('This is not a valid Plant Secretary backup.');if(!confirm('Importing this backup will replace the app’s current saved data. Continue?'))return;localStorage.clear();Object.entries(o.data.localStorage).forEach(([k,v])=>localStorage.setItem(k,v));if(o.data.photos&&typeof o.data.photos==='object'){const d=await window.db();await new Promise((res,rej)=>{const tx=d.transaction('photos','readwrite');const st=tx.objectStore('photos');st.clear();Object.entries(o.data.photos).forEach(([k,v])=>st.put(dataURLBlob(v),k));tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}alert('Backup restored. Plant Secretary will reload now.');location.reload()}
function backup(){showSheet('Backup & Restore',`<p class="hint">Export all supported saved app data to a JSON backup, or restore a Plant Secretary backup.</p><div class="actions"><button class="primary" id="exportBackup">Export backup</button><label class="secondary" style="text-align:center;cursor:pointer">Import backup<input id="importBackup" type="file" accept="application/json,.json" hidden></label></div><p class="hint" id="backupError" style="color:var(--danger);margin-top:12px"></p>`);$('#exportBackup').onclick=exportBackup;$('#importBackup').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await importBackup(f)}catch(err){$('#backupError').textContent=err.message}}}
const actions={'Care Guides':generalGuides,'Plant Notes':notes,'Reminders':reminders,'Weather':weather,'Backup & Restore':backup,'Settings':settings,'About Plant Secretary':about};
document.addEventListener('click',e=>{const card=e.target.closest('.more-card');if(card){const name=card.querySelector('b')?.textContent.trim();if(actions[name]){actions[name]();return}}const t=e.target.closest('.care-topic');if(t){topic(t.dataset.topic);return}const row=e.target.closest('#plantProfile .guide-row');if(row){const name=row.querySelector('b')?.textContent.trim();if(name){topic(name);return}}});
// Make More cards and profile guide rows visibly tappable without altering layout.
const st=document.createElement('style');st.textContent='.more-card{cursor:pointer}.more-card:active,.guide-row:active{transform:scale(.985)}#plantProfile .guide-row{cursor:pointer}';document.head.appendChild(st);
})();