(()=>{
const norm=s=>String(s||'').trim().toLowerCase().replace(/[×]/g,'x').replace(/[‘’]/g,"'").replace(/\s+/g,' ');
const R=(botanical,interval,light,ph,demand,soil,feed,prune,water,sunlight,habit,propagation,problems,seasonal,repotting,pinching,source)=>({botanical,interval,light,ph,demand,soil,feed,prune,water,sunlight,habit,propagation,problems,seasonal,repotting,pinching,source,status:'verified'});
const records={
'adiantum capillus-veneris':R('Adiantum capillus-veneris',3,'indirect','Neutral to alkaline','moist',['Moist but free-draining potting medium','Do not allow the root zone to become waterlogged'],['Feed lightly during active growth only','Avoid heavy feeding; maintain steady moisture instead'],'Trim faded growth in winter if required, or wait until new spring growth emerges.','Keep the medium consistently moist but well-drained; do not allow prolonged drying or waterlogging.','Partial to full shade; indoors use bright filtered/indirect light and shelter from hot direct sun.','Low-growing, spreading, clump-forming fern with arching divided fronds on wiry dark stems.','Division or spores.','RHS lists the species as generally pest-free and disease-free; indoor stress is commonly associated with drying or unsuitable exposure.','Semi-evergreen in warm sheltered conditions or as a houseplant; maintain moisture through active growth and protect from harsh exposure.','Repot when rootbound or when the potting medium has deteriorated, retaining a moist but free-draining medium.','Not required; remove faded growth rather than pinching.','RHS Adiantum capillus-veneris'),
'begonia maculata':R('Begonia maculata',5,'indirect','Acid to neutral','moist',['Light, well-drained peat-free potting compost','Avoid waterlogging'],['Balanced liquid fertiliser during active growth','RHS: at alternate waterings while growing'],'Cut over-long canes to 2–3 buds in late spring','Water moderately in active growth; keep moist but never waterlogged.','Bright filtered light; shade from hot/direct sun.','Erect cane-forming evergreen begonia.','Stem cuttings.','Mealybugs, mites, thrips, aphids; grey mould, powdery mildew and stem/root rot.','Warm growing conditions; protect from cold and hot direct sun.','Repot when roots or compost condition require it; retain free drainage.','Pinch only if shaping is needed; main pruning is cane reduction.','RHS Begonia maculata'),
"philodendron 'birkin'":R("Philodendron 'Birkin'",7,'indirect','Acid, neutral or alkaline','regular',['Standard well-drained houseplant compost','Moist but well-drained; do not leave saturated'],['Balanced liquid fertiliser','Monthly during the growing season'],'No routine pruning required.','Water freely in the growing season; moderately at other times.','Bright filtered or indirect light.','Compact upright, bushy Philodendron cultivar; not a trailer.','Stem-tip or leaf-bud cuttings.','Scale insects and glasshouse red spider mite.','Reduce watering outside active growth; keep warm and sheltered.','RHS recommends repotting every 2–3 years.','Not routinely required.','RHS Philodendron Birkin'),
'sedum morganianum':R('Sedum morganianum',14,'sun','Neutral to alkaline','dry',['Peat-free loam-based compost with added perlite','Very free draining'],['Half-strength liquid fertiliser','Monthly in the growing season'],'No routine pruning required.','Water in the growing season only after drainage is assured; water sparingly in winter.','Bright filtered light; species is listed for full sun outdoors.','Trailing evergreen succulent.','Division or seed; detached healthy material may also root.','Vine-weevil grubs, scale, mealybugs; crown/root rots.','Markedly reduce water in winter.','Repot only as needed; handle fragile leaves carefully.','Not required.','RHS Sedum morganianum'),
'coriandrum sativum':R('Coriandrum sativum',2,'sun','Not numerically established by selected source','moist',['Fertile, free-draining soil or peat-free multipurpose compost','Containers must drain freely'],['Generally light feeding; avoid forcing soft growth','Short-lived annual crop'],'Harvest regularly; remove flower stems if growing for leaves.','Container plants: check frequently and keep compost just moist; never soggy. Ground plants mainly need water in dry spells.','Sun or light shade; summer leaf crops benefit from protection from midday heat.','Fast-growing annual herb.','Seed; direct sowing preferred because coriander dislikes transplanting.','Hot/dry conditions trigger bolting; protect seedlings from slugs/snails.','Successive sowings provide continued leaf harvests; dies after seed set.','Usually grown as a short crop rather than routinely repotted.','Not applicable; harvest leaves and remove unwanted flower stems.','RHS Coriandrum sativum'),
'pilea involucrata':R('Pilea involucrata',5,'indirect','Acid, neutral or alkaline','moist',['Standard houseplant compost','Moist but well-drained'],['Balanced liquid feed','Monthly during active growth'],'Pinch growing tips to promote bushiness.','Water moderately in the growing season; sparingly in winter.','Bright indirect light; sheltered from draughts.','Tender trailing evergreen perennial.','Softwood cuttings.','Generally pest- and disease-free in RHS profile.','High humidity; reduce watering in winter.','Repot when root growth or compost condition requires it.','Pinch growing tips for bushier growth.','RHS Pilea involucrata'),
'gardenia jasminoides':R('Gardenia jasminoides',4,'indirect','Acidic; below pH 7','moist',['Peat-free ericaceous compost','Lime-free, moist but well-drained medium'],['High-nitrogen liquid feed in spring–summer','Balanced feed with trace elements every 5–6 weeks in winter'],'Deadhead fading flowers; shape/prune after flowering as needed.','Spring–summer: keep compost consistently moist, never saturated. Winter: reduce water but do not allow it to dry out. Prefer rainwater in hard-water areas.','Bright light without strong hot sun; sheltered partial shade outdoors in warm weather.','Bushy evergreen tender shrub.','Greenwood or semi-hardwood cuttings; seed also possible.','Whitefly, mealybugs and grey mould; bud drop with temperature swings.','Warm, humid and frost-free; reduce watering in winter while maintaining moisture.','Repot each spring into a container only slightly larger.','Not a pinching-dependent plant; deadhead and shape after flowering.','RHS Gardenia jasminoides'),
'epipremnum aureum':R('Epipremnum aureum',7,'indirect','Acid, neutral or alkaline','regular',['Standard well-drained houseplant compost','Moist but well-drained'],['Balanced liquid fertiliser','Monthly during active growth'],'Tip prune if needed to control/branch growth.','Water freely during active growth; moderately in winter; avoid persistent wetness.','Bright filtered light; tolerates partial shade, but deep shade reduces growth/variegation.','Evergreen aerial-rooting climber.','Stem-tip cuttings or layering.','Mealybugs, scale and spider mites; overwatering can rot roots.','Reduce water in winter; protect from cold draughts.','Repot when rootbound or medium deteriorates.','Tip pruning can encourage branching.','RHS Epipremnum aureum'),
"epipremnum aureum 'marble queen'":R("Epipremnum aureum 'Marble Queen'",7,'indirect','Acid, neutral or alkaline','regular',['Standard houseplant compost','Moist but well-drained'],['Balanced liquid fertiliser','Monthly in the growing season'],'Tip prune in spring to promote branching.','Water freely in the growing season; moderately in winter.','Full or bright filtered light; brighter filtered light supports variegation.','Climbing or trailing evergreen cultivar.','Stem-tip cuttings in summer or layering.','Mealybugs, scale and spider mites.','Reduce watering in winter and protect from cold.','Repot when rootbound or compost degrades.','Tip prune in spring for branching.','RHS Epipremnum aureum Marble Queen'),
'monstera deliciosa':R('Monstera deliciosa',7,'indirect','Acid, neutral or alkaline','regular',['Peat-free loam-based potting compost','Moist but well-drained; humus-rich medium'],['Balanced liquid fertiliser','Monthly while actively growing'],'Prune to control size and remove damaged growth.','Water during active growth; keep only just moist in winter.','Bright indirect light indoors; partial shade outdoors in suitable warmth.','Large evergreen climbing shrub with aerial roots.','Seed, root-tip or stem cuttings.','Scale insects and spider mites; otherwise generally disease-free.','Warm, humid conditions; minimum warmth is important. Reduce water in winter.','Repot as needed and provide climbing support.','Not normally pinched; prune stems for size/shape.','RHS Monstera deliciosa'),
'callisia repens':R('Callisia repens',7,'indirect','Acid, neutral or alkaline','regular',['Two parts peat-free John Innes No. 2 to one part grit','Well-drained'],['Liquid fertiliser','Monthly during active growth'],'No routine pruning required; trim to shape if desired.','Water freely in the growing season; reduce outside active growth while avoiding prolonged saturation.','Bright filtered light.','Matforming, trailing tender evergreen perennial.','Softwood/root cuttings or division of rooted offsets.','Generally pest- and disease-free in RHS profile.','Keep above about 10°C outdoors; best as a protected house/container plant in cool climates.','Repot when crowded; maintain gritty drainage.','Optional for shape only.','RHS Callisia repens'),
'dracaena trifasciata':R('Dracaena trifasciata',14,'indirect','Neutral to alkaline','dry',['Very well-drained loam/sand-based compost','Protect from winter wet'],['Light feeding only during active growth','Avoid heavy feeding'],'No routine pruning required.','Allow the medium to dry substantially between waterings; keep particularly dry in winter.','Bright filtered light indoors; tolerates partial shade. Avoid harsh full summer sun behind glass.','Clump-forming rhizomatous succulent perennial.','Leaf cuttings, suckers or division.','Vine weevil may occur; overwatering/winter wet is the major cultural risk.','Protect from winter wet and cold.','Pot on only when pot-bound.','Not required.','RHS Dracaena trifasciata'),
'curio rowleyanus':R('Curio rowleyanus',14,'sun','Neutral','dry',['Free-draining cactus/succulent compost','Low moisture retention'],['Succulent/cactus feed only during active growth','Do not overfeed'],'Trim weak or straggly stems to the base.','Allow compost to dry between light waterings; water sparingly in winter, only enough to prevent severe shrivelling.','Bright position with several hours of direct sun.','Trailing evergreen succulent.','Softwood/internodal cuttings or division in spring–summer.','Whitefly, aphids and spider mites; stem rot from excessive damp.','Warm growing season; cooler and much drier in winter.','Repot only when needed into a freely draining medium.','Not required; trim weak stems instead.','RHS Curio rowleyanus'),
'haworthia cymbiformis':R('Haworthia cymbiformis',14,'indirect','Not established in selected species source','dry',['Free-draining succulent compost with substantial mineral grit','Never allow prolonged saturation'],['Low-strength succulent fertiliser only in active growth','Avoid excess feeding'],'Remove only dead/damaged leaves or spent flower stalks.','Water thoroughly then allow the medium to dry well before watering again; reduce in cold/low-light periods.','Bright filtered light; protect from harsh hot sun.','Stemless rosette-forming succulent perennial.','Offsets/division; seed is also possible.','Primary cultural risk is rot from excessive moisture.','Reduce watering in cold/low-light periods.','Repot when crowded by offsets or medium has broken down.','Not required.','RHS Haworthia cymbiformis; RHS Haworthia cultivation principles'),
'zamioculcas zamiifolia':R('Zamioculcas zamiifolia',18,'low','Acid, neutral or alkaline','dry',['Well-drained houseplant compost','Loam/sand type medium; avoid saturation'],['Light balanced feeding during active growth','Drought-adapted rhizomes mean heavy feeding is unnecessary'],'No routine pruning; remove faded leaves/flowers at soil level.','Water sparingly and allow compost to dry between waterings; overwatering risks rhizome/root rot.','Indirect light to full shade; filtered light is ideal.','Bushy evergreen rhizomatous perennial with water-storing rhizomes.','Leaf cuttings using single leaflets.','Generally pest- and disease-free; overwatering is the main cultural risk.','Growth slows in cooler/darker periods; water less then.','Repot when rhizomes crowd the container.','Not required.','RHS Zamioculcas zamiifolia'),
'citrus x microcarpa':R('Citrus × microcarpa',5,'sun','Acid to neutral','regular',['Loam-based, moist but well-drained citrus/container compost','Excellent drainage is essential'],['Citrus fertiliser following label directions','Feed during active growth; citrus has sustained nutrient demand'],'Prune lightly for shape and remove dead/crossing growth.','Keep evenly moist during active growth but never waterlogged; reduce in cooler low-growth periods.','Very bright light/full sun with shelter from extremes.','Bushy evergreen citrus shrub.','Semi-ripe cuttings, layering or seed; seed may not reproduce cultivar traits.','Scale, mealybugs, mites and other citrus pests may occur.','Protect from frost/cold; growth and water demand fall in cool periods.','Repot when rootbound into a slightly larger well-drained container.','Not normally required.','RHS Citrus calamondin / Citrus × microcarpa'),
'capsicum annuum':R('Capsicum annuum',3,'sun','Not numerically established by selected RHS species source','moist',['Fertile peat-free compost or good garden soil','Moist but well-drained'],['High-potassium liquid fertiliser','Begin once first fruit has set'],'Pinch growing tips around 20 cm tall to encourage bushiness; harvest fruit regularly.','Water regularly; avoid repeated wilting and waterlogging.','Sunny, warm, sheltered position.','Tender branching Capsicum grown as annual/perennial depending climate.','Seed.','Aphids, whitefly, spider mite; grey mould and blossom-end rot can occur.','Protect from frost; productivity depends on warmth and light.','Container plants may be potted on as roots fill the pot.','Pinch growing tips to encourage bushiness.','RHS Capsicum annuum / chilli cultivation'),
'capsicum chinense':R('Capsicum chinense',3,'sun','Not numerically established by selected RHS species source','moist',['Fertile, well-drained vegetable/container compost','Keep evenly moist without waterlogging'],['High-potassium liquid fertiliser after fruit set','Avoid excessive nitrogen once fruiting'],'Pinch young growing tips for bushiness if needed; harvest ripe fruit.','Water regularly through active growth and fruiting; avoid drought swings.','Maximum warm bright sun; sheltered from cold wind.','Bushy tender Capsicum species including habanero-type chillies.','Seed.','Aphids, whitefly and spider mites; blossom-end rot can follow irregular water/calcium uptake.','Long warm season required; protect from frost and cold.','Pot on as roots fill containers while maintaining drainage.','Pinch young tips if a bushier framework is wanted.','RHS Capsicum chinense / chilli cultivation'),
'citrus limon':R('Citrus limon',6,'sun','Acid to neutral','regular',['Peat-free loam-based potting compost with added grit','Moist but well-drained'],['Citrus-specific fertiliser','Follow manufacturer directions through the year'],'Light pruning for shape; remove dead/damaged/crossing growth.','Water freely in spring–summer growth; sparingly in winter without allowing damaging drought.','Full light; shade from extreme hot sun through glass.','Bushy evergreen citrus shrub/tree.','Semi-ripe cuttings, layering or seed; seedlings do not come true to type.','Scale, mealybugs and spider mites may occur.','Strong spring–summer growth; much lower winter water demand.','Repot when rootbound into well-drained citrus/container compost.','Not normally required.','RHS Citrus × limon'),
'petroselinum crispum':R('Petroselinum crispum',3,'part','Neutral to alkaline preferred','moist',['Fertile, moist but well-drained soil','Rich container compost with reliable drainage'],['Moderate balanced feeding for container crops','Avoid excessive feeding'],'Harvest leaves; remove flowers unless seed is wanted.','Keep actively growing plants evenly moist, especially in containers.','Full sun or partial shade.','Bushy biennial herb, commonly grown as an annual.','Seed sown in situ.','Carrot fly, aphids, celery leaf miner; leaf spot/virus may occur.','First year is leafy; second year flowers and sets seed.','Usually replaced rather than repeatedly repotted.','Not normally pinched.','RHS Petroselinum crispum'),
'salvia rosmarinus':R('Salvia rosmarinus',10,'sun','Neutral to alkaline preferred','dry',['Poor to moderately fertile, very well-drained soil','Loam-based container compost with strong drainage'],['Feed lightly; avoid lush high-nitrogen growth','Established plants need modest fertility'],'Trim after flowering/annually to maintain compact bushy growth; avoid cutting hard into old leafless wood.','Established plants tolerate drought; allow soil to dry somewhat between waterings. Containers need regular checks but must never remain waterlogged.','Full sun.','Evergreen aromatic bushy Mediterranean shrub.','Semi-ripe cuttings in summer or seed.','Rosemary beetle, leafhopper, scale; root/foot rot in wet conditions.','Protect container roots in severe cold; winter wet is more dangerous than moderate dryness.','Repot container plants when rootbound while preserving excellent drainage.','Regular light tip harvesting helps maintain bushiness.','RHS Salvia rosmarinus'),
'eucalyptus cinerea':R('Eucalyptus cinerea',7,'sun','Acid to neutral','regular',['Well-drained neutral-to-acid loam or sandy soil','Avoid waterlogged conditions'],['Generally modest feeding; avoid high-phosphorus native-plant overfeeding','Feed only if growth/substrate indicates need'],'Pruning group 1; coppice/pollard if juvenile foliage is the objective.','Water regularly while establishing; established trees tolerate drier soil. Container specimens require closer moisture checks.','Full sun.','Fast-growing evergreen tree with spreading/bushy habit and silver juvenile foliage.','Seed at 13–18°C in spring/summer.','Eucalyptus gall wasp/sucker; silver leaf, oedema and honey fungus may occur.','Once established, tolerates drier conditions; young/container plants need more reliable moisture.','Container culture is temporary for a potentially large tree; pot on or plant out before severe root restriction.','Not normally pinched; use intentional pruning/coppicing strategy.','RHS Eucalyptus cinerea'),
'hypoestes phyllostachya':R('Hypoestes phyllostachya',5,'indirect','Acid to neutral','regular',['Peat-free loam-based potting compost','Well-drained while retaining enough moisture for active growth'],['Balanced liquid fertiliser','Every 2–3 weeks in summer'],'No structural pruning required; pinch growing tips to maintain a compact bushy plant.','Let the top of the compost begin to dry, then water; water freely in active growth and more sparingly in winter.','Bright indirect/filtered light; avoid direct summer sun and deep shade.','Compact bushy evergreen sub-shrub.','Seed, softwood cuttings in late spring or semi-ripe cuttings in summer.','Powdery mildew may occur; dry air can brown foliage.','Warm, humid conditions; reduce watering in winter.','Repot when rootbound, retaining a well-drained loam-based medium.','Pinch growing tips and remove flower spikes if maintaining compact foliage growth.','RHS Hypoestes phyllostachya'),
'cheiridopsis pillansii':R('Cheiridopsis pillansii',14,'sun','Not established in selected authoritative cultivation source','dry',['Sandy, mineral-rich, extremely well-drained substrate','High mineral fraction; root rot risk in moisture-retentive media'],['Little to no fertiliser','Species thrives in poor soil and is sensitive to excess potassium'],'No routine pruning; remove only fully dry loose material.','Winter-growing mesemb: water more during autumn–spring active growth only after the substrate dries; in summer dormancy water minimally, only if significant shrivelling occurs.','Bright sunny or light shade in the cool growing season; keep cooler/shaded from harsh summer heat.','Small cushion-forming succulent subshrub.','Seed or cuttings.','Root rot from excess moisture; epidermal splitting/scarring from excess water.','Active mainly in the cool season; summer dormancy requires very low water.','Repot only when necessary into a shallow, exceptionally free-draining mineral medium.','Not required.','Kew POWO identity + LLIFLE cultivation')
};
const aliases={"philodendron birkin":"philodendron 'birkin'","epipremnum aureum marble queen":"epipremnum aureum 'marble queen'","citrus × microcarpa":"citrus x microcarpa","citrus × limon":"citrus limon"};
const needsIdentification={
'adiantum':'Species required: Adiantum is a genus, not a species-specific botanical identity.',
'mentha':'Species/cultivar required: Mentha is a genus and mint care can differ by species.',
'phalaenopsis':'Species/hybrid identity required: Phalaenopsis alone is a genus-level identity.',
'spathiphyllum':'Species/cultivar required: Spathiphyllum alone is a genus-level identity.',
'bougainvillea':'Species/cultivar required: Bougainvillea alone is a genus-level identity.',
'mesembryanthemum / delosperma':'Identification required: this saved value contains two different genera and cannot support a species-specific guide.'
};
function keyFor(botanical){const k=norm(botanical);return aliases[k]||k}
function get(botanical){return records[keyFor(botanical)]||null}
function identificationIssue(botanical){return needsIdentification[keyFor(botanical)]||null}
function applyToPlant(p){const r=get(p?.botanical);if(!p||!r)return false;if(Number.isFinite(r.interval))p.interval=r.interval;if(r.light)p.light=r.light;if(r.ph)p.ph=r.ph;if(r.demand)p.demand=r.demand;return true}
function hydrateAll(){let changed=false;try{const list=typeof plants!=='undefined'?plants:(window.plants||[]);for(const p of list||[])if(applyToPlant(p))changed=true}catch(_){}return changed}
window.PLANT_BOTANICAL_CARE={normalize:norm,get,identificationIssue,applyToPlant,hydrateAll,records};
const originalSave=window.save;if(typeof originalSave==='function'){window.save=function(){hydrateAll();return originalSave.apply(this,arguments)};try{save=window.save}catch(_){}}
if(hydrateAll()&&typeof originalSave==='function')originalSave();
})();