(()=>{
const KEY='plant-secretary-photo-view-v1';
const $=s=>document.querySelector(s);
function views(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function saveViews(v){localStorage.setItem(KEY,JSON.stringify(v))}
function state(id){const v=views();return v[id]||{x:0,y:0,scale:1}}
function applyTo(img,id){if(!img)return;const v=state(id);img.style.width='100%';img.style.height='100%';img.style.objectFit='cover';img.style.transformOrigin='center center';img.style.transform=`translate(${v.x}%,${v.y}%) scale(${v.scale})`;img.style.willChange='transform'}
function applyAll(){document.querySelectorAll('[id^="photo-"] img').forEach(img=>applyTo(img,img.parentElement.id.replace('photo-','')));const hero=document.querySelector('[id^="hero-"] img');if(hero)applyTo(hero,hero.parentElement.id.replace('hero-',''))}
async function getPhotoFor(id){try{return await getPhoto(id)}catch(e){return null}}
function ensureModal(){let m=$('#photoAdjustModal');if(m)return m;m=document.createElement('div');m.id='photoAdjustModal';m.className='modal';m.innerHTML=`<div class="sheet"><div class="sheethead"><h3>Adjust Photo</h3><button class="close" id="photoAdjustClose">×</button></div><p class="hint">Drag the photo to move it. Use the slider to resize the photo. The original uploaded file is not changed.</p><div id="photoAdjustStage" style="position:relative;width:100%;aspect-ratio:4/3;border-radius:18px;overflow:hidden;background:linear-gradient(145deg,#e8f6ef,#eee8fb);touch-action:none"><img id="photoAdjustImg" alt="Plant photo" style="width:100%;height:100%;object-fit:cover;transform-origin:center center;user-select:none;-webkit-user-drag:none"></div><label style="display:block;margin-top:14px;font-size:13px;color:#59677c">Resize<input id="photoZoom" type="range" min="1" max="2.5" step="0.01" value="1" style="width:100%;margin-top:8px"></label><div class="actions"><button class="secondary" id="photoReset">Reset</button><button class="primary" id="photoSave">Save view</button></div>`;document.body.appendChild(m);m.querySelector('#photoAdjustClose').onclick=()=>m.classList.remove('open');m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});return m}
async function openEditor(id){const blob=await getPhotoFor(id);if(!blob){if(typeof toast==='function')toast('Upload a photo first');return}const m=ensureModal(),img=$('#photoAdjustImg'),zoom=$('#photoZoom'),stage=$('#photoAdjustStage');let v={...state(id)};const url=URL.createObjectURL(blob);img.src=url;function draw(){img.style.transform=`translate(${v.x}%,${v.y}%) scale(${v.scale})`;zoom.value=v.scale}draw();let dragging=false,lastX=0,lastY=0;stage.onpointerdown=e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;stage.setPointerCapture?.(e.pointerId)};stage.onpointermove=e=>{if(!dragging)return;const r=stage.getBoundingClientRect();v.x+=((e.clientX-lastX)/r.width)*100;v.y+=((e.clientY-lastY)/r.height)*100;v.x=Math.max(-60,Math.min(60,v.x));v.y=Math.max(-60,Math.min(60,v.y));lastX=e.clientX;lastY=e.clientY;draw()};stage.onpointerup=stage.onpointercancel=()=>dragging=false;zoom.oninput=()=>{v.scale=Number(zoom.value);draw()};$('#photoReset').onclick=()=>{v={x:0,y:0,scale:1};draw()};$('#photoSave').onclick=()=>{const all=views();all[id]=v;saveViews(all);m.classList.remove('open');URL.revokeObjectURL(url);applyAll();if(typeof renderCollection==='function')renderCollection();setTimeout(applyAll,50);if($('#plantModal')?.classList.contains('open')&&typeof openModal==='function'){openModal(id);setTimeout(applyAll,50)}if(typeof toast==='function')toast('Photo position and size saved')};m.classList.add('open')}
// Intercept photo taps before the parent plant-card profile click handler.
document.addEventListener('click',e=>{const box=e.target.closest('.photo,.hero-photo');if(!box)return;const id=box.id?.replace(/^photo-|^hero-/,'');if(!id)return;e.preventDefault();e.stopPropagation();openEditor(id)},true);
const obs=new MutationObserver(()=>applyAll());obs.observe(document.body,{childList:true,subtree:true});setTimeout(applyAll,0);
})();