(()=>{
const KEY='plant-secretary-photo-view-v1';
const $=s=>document.querySelector(s);
function views(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function saveViews(v){localStorage.setItem(KEY,JSON.stringify(v))}
function clean(v){const s=Math.max(1,Math.min(2.5,Number(v?.scale)||1));let x=Number(v?.x)||0,y=Number(v?.y)||0;if(Math.abs(x)>1)x/=60;if(Math.abs(y)>1)y/=60;return{x:Math.max(-1,Math.min(1,x)),y:Math.max(-1,Math.min(1,y)),scale:s}}
function state(id){return clean(views()[id]||{x:0,y:0,scale:1})}
function transformFor(img,v){const box=img.parentElement?.getBoundingClientRect();const w=box?.width||img.clientWidth||1,h=box?.height||img.clientHeight||1;const maxX=w*(v.scale-1)/(2*v.scale),maxY=h*(v.scale-1)/(2*v.scale);return `scale(${v.scale}) translate3d(${v.x*maxX}px,${v.y*maxY}px,0)`}
function applyTo(img,id){if(!img)return;const v=state(id);img.style.width='100%';img.style.height='100%';img.style.objectFit='cover';img.style.transformOrigin='center center';img.style.transform=transformFor(img,v);img.style.willChange='transform'}
function applyAll(){document.querySelectorAll('[id^="photo-"] img').forEach(img=>applyTo(img,img.parentElement.id.replace('photo-','')));document.querySelectorAll('[id^="hero-"] img').forEach(img=>applyTo(img,img.parentElement.id.replace('hero-','')))}
async function getPhotoFor(id){try{return await getPhoto(id)}catch(e){return null}}
function ensureModal(){let m=$('#photoAdjustModal');if(m)return m;m=document.createElement('div');m.id='photoAdjustModal';m.className='modal';m.innerHTML=`<div class="sheet"><div class="sheethead"><h3>Adjust Photo</h3><button class="close" id="photoAdjustClose">×</button></div><p class="hint">Drag to reposition. Resize with the slider. The crop always stays filled, and the original uploaded photo is never changed.</p><div id="photoAdjustStage" style="position:relative;width:100%;aspect-ratio:4/3;border-radius:18px;overflow:hidden;background:linear-gradient(145deg,#e8f6ef,#eee8fb);touch-action:none"><img id="photoAdjustImg" alt="Plant photo" style="width:100%;height:100%;object-fit:cover;transform-origin:center center;user-select:none;-webkit-user-drag:none"></div><label style="display:block;margin-top:14px;font-size:13px;color:#59677c">Resize<input id="photoZoom" type="range" min="1" max="2.5" step="0.01" value="1" style="width:100%;margin-top:8px"></label><div class="actions"><button class="secondary" id="photoReset">Reset</button><button class="primary" id="photoSave">Save view</button></div>`;document.body.appendChild(m);m.querySelector('#photoAdjustClose').onclick=()=>m.classList.remove('open');m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});return m}
async function openEditor(id){const blob=await getPhotoFor(id);if(!blob){if(typeof toast==='function')toast('Upload a photo first');return}const m=ensureModal(),img=$('#photoAdjustImg'),zoom=$('#photoZoom'),stage=$('#photoAdjustStage');let v=state(id);const url=URL.createObjectURL(blob);img.src=url;
function draw(){v=clean(v);img.style.transform=transformFor(img,v);zoom.value=v.scale}
img.onload=draw;draw();let dragging=false,lastX=0,lastY=0;
stage.onpointerdown=e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;stage.setPointerCapture?.(e.pointerId)};
stage.onpointermove=e=>{if(!dragging)return;const r=stage.getBoundingClientRect(),maxX=r.width*(v.scale-1)/(2*v.scale),maxY=r.height*(v.scale-1)/(2*v.scale);if(maxX>0)v.x+=((e.clientX-lastX)/maxX);if(maxY>0)v.y+=((e.clientY-lastY)/maxY);v.x=Math.max(-1,Math.min(1,v.x));v.y=Math.max(-1,Math.min(1,v.y));lastX=e.clientX;lastY=e.clientY;draw()};
stage.onpointerup=stage.onpointercancel=()=>dragging=false;
zoom.oninput=()=>{v.scale=Number(zoom.value);if(v.scale<=1){v.x=0;v.y=0}draw()};
$('#photoReset').onclick=()=>{v={x:0,y:0,scale:1};draw()};
$('#photoSave').onclick=()=>{const all=views();all[id]=clean(v);saveViews(all);m.classList.remove('open');URL.revokeObjectURL(url);applyAll();if(typeof renderCollection==='function')renderCollection();setTimeout(applyAll,80);if($('#plantModal')?.classList.contains('open')&&typeof openModal==='function'){openModal(id);setTimeout(applyAll,80)}if(typeof toast==='function')toast('Photo position and size saved')};m.classList.add('open')}
document.addEventListener('click',e=>{const box=e.target.closest('.photo,.hero-photo');if(!box)return;const id=box.id?.replace(/^photo-|^hero-/,'');if(!id)return;e.preventDefault();e.stopPropagation();openEditor(id)},true);
const obs=new MutationObserver(()=>requestAnimationFrame(applyAll));obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('resize',applyAll);setTimeout(applyAll,0);
})();