const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const root=path.join(__dirname,'..');
function setup(){const document={querySelector:()=>null,createElement:()=>({}),head:{appendChild(){}},addEventListener(){}};const ctx=vm.createContext({window:{},document});for(const f of ['watering-audit.js','botanical-care.js','practical-care.js','care-presentation.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);let code=fs.readFileSync(path.join(root,'app-actions.js'),'utf8').replace(/\}\)\(\);\s*$/,'window.testCare={topicHtml};})();');vm.runInContext(code,ctx);return ctx}
test('weather and watering notes are collapsed for every resolved guide while practical advice and the seasonal table stay visible',()=>{
 const c=setup();for(const d of Object.values(c.window.PLANT_PRACTICAL_CARE.records)){
  const p={name:'User plant',botanical:d.botanical,location:'Indoor',wateringCheckDays:14,history:[{type:'Watered',date:'2026-10-01'}],photoId:'keep'};
  const before=JSON.stringify(p),html=c.window.testCare.topicHtml('Watering checks',p);
  const notes=html.match(/<details class="care-watering-notes"><summary>Weather &amp; watering notes<\/summary>([\s\S]*?)<\/details>/);
  assert.ok(notes,d.botanical);assert.match(notes[1],/BOM|Altona/);assert.match(notes[1],/Outdoor rainfall cannot determine/);assert.match(notes[1],/droplet records actual watering only/);
  assert.doesNotMatch(html,/<details class="care-watering-notes"[^>]*\bopen\b/);
  const remaining=html.replace(notes[0],'');assert.match(remaining,/<table>/);assert.match(remaining,/Practical steps/);assert.doesNotMatch(remaining,/Outdoor rainfall cannot determine|droplet records actual watering only/);
  assert.equal(JSON.stringify(p),before);assert.equal(c.window.PLANT_WATERING_AUDIT.interval(p),14);
 }
});
test('optional weather-free description preserves the original API and moisture advice without changing settings',()=>{
 const c=setup(),a=c.window.PLANT_WATERING_AUDIT,p={botanical:'Peperomia argyreia',location:'Indoor',wateringCheckDays:5};
 const full=a.describe(p),visible=a.describe(p,new Date(),false);
 assert.match(full,/Outdoor rainfall cannot determine/);assert.doesNotMatch(visible,/Outdoor rainfall cannot determine|droplet records/);
 assert.match(visible,/Inspect every 5 days/);assert.match(visible,/Inspect the upper mix/);assert.equal(a.summary(p),'Check every 5 days.');
});
test('every practical botanical identity has a non-empty soil requirement, named retailer match and scoped season table',()=>{const c=setup(),d=c.window.PLANT_PRACTICAL_CARE,presentation=c.window.PLANT_CARE_PRESENTATION;for(const record of Object.values(d.records)){const p={name:'Same display name',botanical:record.botanical,location:'Outdoor',history:[{type:'Watered',date:'2026-10-01'}],photoId:'keep',wateringCheckDays:17};const before=JSON.stringify(p);const soil=presentation.soilInfo(p),season=presentation.seasonalInfo(p);assert.ok(soil.description.length>20,record.botanical);assert.ok(soil.products.length,record.botanical);for(const product of soil.products)assert.match(product.url,/^https:\/\/www.bunnings.com.au\//);assert.ok(season.rows.length>=3);assert.ok(season.sources.some(s=>s.url.includes('bom.gov.au')));const html=c.window.testCare.topicHtml('Watering checks',p);assert.match(html,/<table>/);assert.match(html,/Seasonal evidence gaps/);assert.doesNotMatch(html,/undefined|\[object Object\]/);assert.equal(JSON.stringify(p),before);assert.equal(c.window.PLANT_WATERING_AUDIT.interval(p),17)}});
test('botanical punctuation and explicit cultivars resolve without changing saved names or using display names',()=>{const c=setup(),d=c.window.PLANT_PRACTICAL_CARE;for(const [botanical,canonical] of [['Origanum vulgare subsp. hirtum.','Origanum vulgare subsp. hirtum'],['Epipremnum aureum ‘Goldilocks’',"Epipremnum aureum 'Goldilocks'"],['Philodendron hederaceum ‘Brasil’',"Philodendron hederaceum 'Brasil'"],['Thymus vulgaris','Thymus vulgaris']]){const p={name:'ZZ Plant',botanical};const before=JSON.stringify(p);assert.equal(d.getCare(botanical).botanical,canonical);assert.ok(c.window.PLANT_CARE_PRESENTATION.soilInfo(p));assert.equal(JSON.stringify(p),before)}assert.equal(d.getCare('Goldilocks Gold'),null);assert.match(d.getCare('Epipremnum aureum ‘Goldilocks’').identityNote,/species/)});
test('blank means no interval, including Meyer, summers, legacy values and unresolved identities',()=>{const c=setup(),a=c.window.PLANT_WATERING_AUDIT;for(const botanical of ["Citrus × limon 'Meyer'",'Capsicum annuum','Unknown'])for(const date of [new Date('2026-01-07'),new Date('2026-07-07')]){const p={botanical,location:'Outdoor',interval:7};assert.equal(a.interval(p,date),null);assert.equal(a.summary(p,date),'');p.wateringCheckDays=14;assert.equal(a.interval(p,date),14);assert.equal(a.summary(p,date),'Check every 14 days.')}});
test('only documented edible-container summer guidance uses a numerical frequency; no dormancy copied to ice plant',()=>{const c=setup(),api=c.window.PLANT_CARE_PRESENTATION;let info=api.seasonalInfo({botanical:'Capsicum annuum',location:'Outdoor'});assert.match(info.rows[1][1],/At least daily checks/);assert.ok(info.sources.some(s=>s.url.includes('potted-produce')));assert.doesNotMatch(api.seasonalInfo({botanical:'Capsicum annuum',location:'Indoor'}).rows.flat().join(' '),/At least daily/);assert.doesNotMatch(api.seasonalInfo({botanical:'Capsicum annuum',location:'Outdoor',growingIn:'ground'}).rows.flat().join(' '),/At least daily/);assert.match(api.seasonalInfo({botanical:'Cheiridopsis pillansii'}).rows.flat().join(' '),/Summer.*dormancy/);assert.doesNotMatch(api.seasonalInfo({botanical:'Delosperma lehmannii'}).rows.flat().join(' '),/Summer — dormancy/);assert.match(api.soilInfo({botanical:'Begonia maculata'}).products[0].basis,/unverified/i);assert.ok(api.soilInfo({botanical:'Begonia maculata'}).products[0].unverified)});
test('unscheduled plants are excluded from due-today filters and styling in both renderers',()=>{for(const file of ['index.html','home-art.js']){const code=fs.readFileSync(path.join(root,file),'utf8');assert.doesNotMatch(code,/daysUntil\(p\)===null\|\|daysUntil\(p\)<=0/);assert.match(code,/daysUntil\(p\)!==null&&daysUntil\(p\)<=0/)}const index=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.ok(index.indexOf('practical-care.js')<index.indexOf('care-presentation.js'));assert.ok(index.indexOf('care-presentation.js')<index.indexOf('app-actions.js'));assert.match(fs.readFileSync(path.join(root,'sw.js'),'utf8'),/care-presentation.js/)});
